name: Package Publish

on:
  push:
    branches: [ release ]

jobs:



   tag:
    name: 'Tag Version'
    runs-on: ubuntu-latest
    steps:
    - name: 'Download New Version'
      uses: actions/download-artifact@v1
      with:
        name: home
    - name: Set and Tag the new version
      uses: tvdias/github-tagger@v0.0.2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        tag: $(cat home/version.txt)